### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException: Could not find the key 'rbs2-content-type' when deserializing messages.

### ISSUE THREAD

**Issue by MaikuMori** [rebus-org/Rebus#690]
I've been trying some strange combination of microservices with different targets (netstandard2, mono-net471, net471)

There seems to be a bug with mono and/or netstandard2.

Correct me if I'm wrong but I believe it's here:

https://github.com/rebus-org/Rebus/blob/master/Rebus/Serialization/Json/JsonSerializer.cs#L76

There is a chance that the header is not defined, but here it's being read in any case:

https://github.com/rebus-org/Rebus/blob/master/Rebus/Serialization/Json/JsonSerializer.cs#L95

**Comment by mookid8000** [comment]
oh, good catch! – I'll fix it right away....

(btw I assume it's Rebus 5.0.0-b06 you're using.... it'll be fixed in 5.0.0-b07 in a few minutes)

**Comment by mookid8000** [comment]
I caught some more conditional compilation issues introduced when I added .NET Core 2 as a target.... it's out in 5.0.0-b08

Thanks for raising this issue 👍

**Comment by MaikuMori** [comment]
Awesome!

**Comment by 201270842** [comment]
Could it be that this issue still exists in 5.2? seems that knuth is still throwing an error when rbs2-content-type is not present in the header. rbs2-msg-id is available.

**Comment by mookid8000** [comment]
Could you post a full stacktrace with the error, you're experiencing? 

That would help a lot 🙂
