### ISSUE TITLE
Deferring directly to other input queue

### ISSUE THREAD

**Issue by martindisch** [rebus-org/Rebus#899]
I'm trying out Rebus and love its powerful simplicity. But I ran into an issue where I either misunderstood a feature, or made some mistake using it. It's probably really easy for you to answer.

I have two independent applications, _Pub_ which manages a Saga `OrderSaga`, and _Bartender_, which is part of that Saga (there are more, but for the sake of example I'll keep it simple). They communicate using Azure Service Bus. There are two queues, one for each. Let's call them `pub.input` and `bartender.input`. Let's imagine their simple communication using two messages as `Pub -> [BeerOrdered] -> Bartender -> [BeerServed] -> Pub`.
_Pub_ is set up as you probably imagine:
```C#
var services = new ServiceCollection()
    .AddRebus(c => c
        .Logging(l => l.Serilog())
        .Sagas(s => s.StoreInMemory())
        .Transport(t => t.UseAzureServiceBus("connstring", "pub.input"))
        .Routing(r => r.TypeBased().Map<BeerOrdered>("bartender.input")))
    .AddRebusHandler<OrderSaga>();
```

Within `OrderSaga` I want to send the `BeerOrdered` message to _Bartender_. But I want to delay it, so that it only arrives in 10 seconds. I thought I could just do this
```C#
await _bus.Defer(TimeSpan.FromSeconds(10), new BeerOrdered(correlationId));
```
and since Rebus knows to route `BeerOrdered` to the input queue `bartender.input` (it works with `_bus.Send`), that's where it would go.

Interestingly, the message will be put into the sender's input queue (`pub.input`) instead. The `DeferredRecipient` header is correctly set to `bartender.input` though. I read through some similar issues like https://github.com/rebus-org/Rebus.AzureServiceBus/issues/49, https://github.com/rebus-org/Rebus/issues/671, https://github.com/rebus-org/Rebus/issues/629 and https://github.com/rebus-org/Rebus/issues/592, but couldn't find anything that worked for me. Debugging led me here
```C#
public async Task Defer(TimeSpan delay, object message, IDictionary<string, string> optionalHeaders = null)
{
    var logicalMessage = CreateMessage(message, Operation.Defer, optionalHeaders);
    var destinationAddress = await _router.GetDestinationAddress(logicalMessage);

    logicalMessage.SetDeferHeaders(_rebusTime.Now + delay, destinationAddress);

    var timeoutManagerAddress = GetTimeoutManagerAddress();

    await InnerSend(new[] { timeoutManagerAddress }, logicalMessage);
}
```
and I noticed that while the headers get set as expected, the `timeoutManagerAddress` that the message actually gets sent to is my input queue `pub.input`.

This looks intentional to me, so I'm assuming that's not a bug but how it should work. I'm sure I'll be able to find a workaround, but before I try, is there an "official" way in Rebus to put a deferred message _directly_ into a different input queue for transports that support deferring/scheduling messages natively?

**Comment by mookid8000** [comment]
Looking at the code I can see that the issue you're describing would occur in cases where a custom queue name convention would somehow mess with a "magic deferred messages destination", which is used internally in the transport.

This magic queue name should of course never be passed through the naming convention, so I've switched the order of operations in the code that detects this.

I've pushed the fix as Rebus.AzureServiceBus 7.1.5 – it should be available on NuGet.org in a few minutes.

Could you try it and see if it fixes your issue?

**Comment by martindisch** [comment]
Thanks for looking into this so quickly! I just checked and sadly it did not fix the issue. But since I now know where to look in the Azure Service Bus implementation, I did some more debugging in there to see what actually happens. This is the code that determines the actual destination address in your newest update:
```C#
string GetActualDestinationAddress(string destinationAddress, TransportMessage message)
{
    if (destinationAddress == MagicDeferredMessagesAddress)
    {
        try
        {
            return message.Headers.GetValue(Headers.DeferredRecipient);
        }
        catch (Exception exception)
        {
            throw new ArgumentException($"The destination address was set to '{MagicDeferredMessagesAddress}', but no '{Headers.DeferredRecipient}' header could be found on the message", exception);
        }
    }

    if (!destinationAddress.StartsWith(MagicSubscriptionPrefix))
    {
        return _nameFormatter.FormatQueueName(destinationAddress);
    }

    return destinationAddress;
}
```
The problem is that the `destinationAddress` that is passed in and evaluated isn't `MagicDeferredMessagesAddress` (`___deferred___`), it's the address of the sender's input queue (in my case `pub.input`). So it never reaches the logic where it extracts the actual destination address from the `DeferredRecipient` header. The root cause is that the detection mechanisms for deferred messages doesn't work.

**Comment by mookid8000** [comment]
ok, bummer 😐 I have time to take a more thorough look at it on Wednesday

**Comment by martindisch** [comment]
No worries, and thank you so much. Let me know if I can help you in any way, for example by setting up a minimal example project you can use for testing.

**Comment by mookid8000** [comment]
I've identified the issue – have published Rebus.AzureServiceBus 7.1.6, which should be visible on NuGet.org in a few minutes.

Sorry for taking so long to get back to this one. 😐 

Thanks for reporting the issue in the first place! 👍

**Comment by martindisch** [comment]
I have tested the solution, it works as expected. Great job, and thank you!
